### PR TITLE
[API] CSV Upload functionality with employee creation using Multer and csv-parser modules

### PR DESCRIPTION
**Pull request by senseihimanshu**

### CODE REVIEW

**Comment by senseihimanshu** [comment]
fixes #50

**Comment by sonalichawla16** [comment]
Resolve conflicts

**Comment by senseihimanshu** [comment]
Done!

**Comment by sonalichawla16** [comment]
Conflicts

**Comment by senseihimanshu** [comment]
Resolved, Kindly Merge

**Pull request merged**
